### ISSUE TITLE
Integrate into CDK

### ISSUE THREAD

**Issue by hoegertn** [aws-samples/cdk-assume-role-credential-plugin#1]
It would be great to integrate this plugin in CDK natively and use the bootstrapped cross-account roles of the new bootstrapping flow.

**Comment by corymhall** [comment]
I totally agree that it would be great to integrate this with the CDK natively or at least be able to use it with the new bootstrapped roles. Currently credential plugins in the CDK are pretty limited in what they can do. They only information that a plugin gets passed is the target account ID and the mode (read or write). 

I'll definitely be continuing to look into this and I'll update this issue as I figure out if there is a solution.

**Comment by hoegertn** [comment]
Feel free to ping me, as I am a contributor to the CDK project. As I understand the limitations the issue might be that we need the region to create the ARN of the bootstrap role but only get the account currently.

**Comment by corymhall** [comment]
Actually, after doing some tests it looks like the plugin will work with the new bootstrapped roles. It looks like if you are setting the `newStyleStackSynthesis` to true it follows these steps:

1. Look for credentials for target account using plugin
2. Publish assets
    2a. Use plugin to assume cdk-writeRole
    2b. Assume file-publishing-role (using default credentials _not_ the cdk-writeRole)
3. Create & Execute change set
    3a. Assume deploy-role role and create/execute change set with role-arn set to cfn-exec role

Based on this it looks like all we need is the `cdk-readOnlyRole` and use it for both modes (read/write). The CDK will only really use the `cdk-readOnlyRole` when performing lookups. In all other cases it still needs to perform the action of assuming the role in the target account, but it doesn't actually use those credentials. Instead it does another assume role call, grabbing credentials from the bootstrapped roles.

_here are logs from a test_
```bash
Reading existing template for stack EcsDemoStack.
AssumeRoleCredentialPlugin found value for readIamRole cdk-readOnlyRole. checking if we can obtain credentials
AssumeRoleCredentialPlugin found value for writeIamRole cdk-writeRole. checking if we can obtain credentials
canProvideCredentails for read role: true
canProvideCredentails for write role: true
Using AssumeRoleCredentialPlugin credentials for account 111111111111
AssumeRoleCredentialPlugin getting credentials for role arn:aws:iam::111111111111:role/cdk-readOnlyRole with mode 0
Retrieved account ID 111111111111 from disk cache
Assuming role 'arn:aws:iam::111111111111:role/cdk-hnb659fds-deploy-role-111111111111-us-east-2'.
Call failed: describeStacks({"StackName":"EcsDemoStack"}) => Stack with id EcsDemoStack does not exist
EcsDemoStack: deploying...
Retrieved account ID 111111111111 from disk cache
Assuming role 'arn:aws:iam::111111111111:role/cdk-hnb659fds-deploy-role-111111111111-us-east-2'.
Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing e5be2852057bd268365b76d73374306b3cb35b33339e285adbbddc24630b244e:111111111111-us-east-2
AssumeRoleCredentialPlugin found value for readIamRole cdk-readOnlyRole. checking if we can obtain credentials
AssumeRoleCredentialPlugin found value for writeIamRole cdk-writeRole. checking if we can obtain credentials
canProvideCredentails for read role: true
canProvideCredentails for write role: true
Using AssumeRoleCredentialPlugin credentials for account 111111111111
AssumeRoleCredentialPlugin getting credentials for role arn:aws:iam::111111111111:role/cdk-writeRole with mode 1
Retrieved account ID 580348834564 from disk cache
Assuming role 'arn:aws:iam::111111111111:role/cdk-hnb659fds-file-publishing-role-111111111111-us-east-2'.
[0%] check: Check s3://cdk-hnb659fds-assets-111111111111-us-east-2/e5be2852057bd268365b76d73374306b3cb35b33339e285adbbddc24630b244e
[0%] upload: Upload s3://cdk-hnb659fds-assets-111111111111-us-east-2/e5be2852057bd268365b76d73374306b3cb35b33339e285adbbddc24630b244e
[100%] success: Published e5be2852057bd268365b76d73374306b3cb35b33339e285adbbddc24630b244e:111111111111-us-east-2
Call failed: describeStacks({"StackName":"EcsDemoStack"}) => Stack with id EcsDemoStack does not exist
EcsDemoStack: checking if we can skip deploy
EcsDemoStack: no existing stack
EcsDemoStack: deploying...
Attempting to create ChangeSet CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3 to create stack EcsDemoStack
EcsDemoStack: creating CloudFormation changeset...
Initiated creation of changeset: arn:aws:cloudformation:us-east-2:111111111111:changeSet/CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3/84e32e8d-3184-445d-acb1-2b55896bb8f2; waiting for it to finish creating...
Waiting for changeset CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3 on stack EcsDemoStack to finish creating...
Changeset CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3 on stack EcsDemoStack is still creating
Initiating execution of changeset CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3 on stack EcsDemoStack
Execution of changeset CDK-defea1a6-acce-4046-b90c-1de8fcc8e7c3 on stack EcsDemoStack has started; waiting for the update to complete...
Waiting for stack EcsDemoStack to finish creating or updating...
Stack EcsDemoStack has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS (User Initiated))
 0/2 | 3:11:49 PM | CREATE_IN_PROGRESS   | AWS::SSM::Parameter | TestParam (TestParam211A9454)
 0/2 | 3:11:50 PM | CREATE_IN_PROGRESS   | AWS::SSM::Parameter | TestParam (TestParam211A9454) Resource creation Initiated
Stack EcsDemoStack has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS)
 2/2 | 3:11:51 PM | CREATE_COMPLETE      | AWS::SSM::Parameter | TestParam (TestParam211A9454)
 2/2 | 3:11:52 PM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | EcsDemoStack
Stack EcsDemoStack has completed updating
```

I can update the plugin & documentation based on this functionality.

**Comment by corymhall** [comment]
@hoegertn the plugin has been updated as much as it can to work with the new bootstrap roles. If you have set the `newStyleStackSynthesis` to `true` then the plugin will behave differently now. When [this issue](https://github.com/aws/aws-cdk/issues/9597) is fixed, the plugin will no longer be needed for anything other than fetching context, but that will also most likely be [addressed soon as well](https://github.com/aws/aws-cdk/issues/9226)

The CLI no longer needs the cdk-writeRole for anything other than a credential check, so the plugin will treat the ForWriting mode a little differently.

- If @aws-cdk/core:newStyleStackSynthesis=true & mode=ForWriting & we are not bootstrapping: then The plugin will simply return the default credentials (will not assume a role). This will satisfy the credential check.

- If @aws-cdk/core:newStyleStackSynthesis=true & mode=ForReading: then The plugin will use the readOnlyRole. Since we don't know whether it is being used to fetch context or simply perform the credential check, we have to assume that it is fetching context.

- If @aws-cdk/core:newStyleStackSynthesis=true & mode=ForWriting & bootstrap=true: then The plugin will use the writeRole.

- Otherwise assume this is using the old style syntesis and use both roles as normal.
