### ISSUE TITLE
Does this plugin work with context lookups?

### ISSUE THREAD

**Issue by zxkane** [aws-samples/cdk-assume-role-credential-plugin#12]
I did try to use this plugin to deploy a CDK app cross account.

But it failed on looking up vpc and R53 hosted zone. Does this plugin also having same limitation as `cdk pipelines`?

**Comment by corymhall** [comment]
@zxkane this plugin does work with context lookups, but only for top level stacks. If you are using `Stages` (required by cdk pipelines) then context lookups do not work. The CDK does not currently support context lookups for stacks defined within a Stage, and this applies to this plugin as well.

**Comment by zxkane** [comment]
Thanks for your explanation.  Looks like I'm blocked by #13 . I'll try to fix it locally. Will submit PR if it works.
