### ISSUE TITLE
partition support

### ISSUE THREAD

**Issue by zxkane** [aws-samples/cdk-assume-role-credential-plugin#13]
Role arn is using hard code partition `aws` to make it not to work in `aws-cn` and gov us partition.

**Comment by corymhall** [comment]
@zxkane were you able to test out a fix locally? If not I can work on an update where you can pass in the partition as another context variable.

**Comment by zxkane** [comment]
Not have a try yet. Hope I can try it in next week.

Cory Hall <notifications@github.com> 于 2020年9月23日周三 下午10:52写道：

**Comment by wojtekwalczak** [comment]
Hi, I've had the same problem as @zxkane. Based on his PR I have created mine.

I believe that the main difference between our PRs is that I check for `yargs.argv?.region` when getting the region information, and I use this information in `getPartition` and in `tryAssumeRole` methods.

Thanks to these modifications I am able to deploy my stack to `aws-cn`. Deployments to `aws` partition work too.

To make it work for `aws-cn` deployments I have to pass the `--region <REGION>` when calling `cdk deploy`, but this solution is good enough for me. For example:

```bash
$ cdk deploy <STACK_NAME> --profile live --region cn-north-1
```
