### ISSUE TITLE
Using aws sdk (boto3) calls across accounts in stacks

### ISSUE THREAD

**Issue by rirze** [aws-samples/cdk-assume-role-credential-plugin#32]
Hi,

I'm unsure if I'm running into a plugin installation problem or a limitation of this plugin (or how I'm supposed to call AWS APIs within stacks).

Essentially, I'd like to know if I should be able to make AWS SDK calls, or specifically boto3 in Python, within stacks when using this plugin. In my current installation, boto3 only uses the profile set in the terminal for all stacks across all accounts. This is not my desired behavior, as I'd like calls made within each stack to only apply to the account that is provided in the stack's Environment object. 

Is this possible or am I asking for a feature that's not yet implemented? Thanks.

**Comment by corymhall** [comment]
@rirze if you are wanting to make AWS SDK calls from within your CDK code that will be executed during synthesis then the SDK will use your profile set in the terminal. At that point you are essentially operating outside of the CDK so you would have to handle making assume role calls yourself with SDK calls.

**Comment by rirze** [comment]
Thanks for the reply.

I ended resorting to another plugin which switches aws profiles when synthesizing stacks. Since those profiles also have sufficient permissions to deploy the stacks, this plugin was superseded by the other one. If I didn't need to call on the SDK (the CDK has some lookup static functions that call on the SDK), then I would've definitely stuck with the practices recommended here.
