### ISSUE TITLE
Docs incorrectly lead to belive, that cdk-hnb659fds-deploy-role is usable with newstyle synthesis

### ISSUE THREAD

**Issue by redbaron** [aws-samples/cdk-assume-role-credential-plugin#35]
Recent CDK versions with new style synthesis are capable of assuming role in the destination account by itself, no plugin needed. Where plugin comes handy is with lookups, which still don't work cross account.

Documentation here points that `readOnlyRole` can be a role from bootstrap stack:

>This is especially handy with the new CDK Bootstrap style because the new bootstrap already creates roles that can be used with this plugin.

But this role is not very usable, all it can do is to call cloudformation, it can't do lookups:

https://github.com/aws/aws-cdk/blob/282d242c513a9bc853e9b96ff782a7823abd5a5a/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L294-L365

Hence there is no much point in using it with newstyle synthesis.

**Comment by moltar** [comment]
This might be fixed by this: https://github.com/aws/aws-cdk/pull/14874

**Comment by redbaron** [comment]
Indeed.

**Comment by mikelhamer** [comment]
@redbaron I use it for cross account deployments. Most recent as in v2?

**Comment by redbaron** [comment]
Cross account should work out of the box with recent enough  v1 too
