### ISSUE TITLE
Unable to use cdk-assume-role-credential-plugin  to deploy resources in HongKong Region (ap-east-1), probably all regions not enabled by default

### ISSUE THREAD

**Issue by XuejiaoZhang** [aws-samples/cdk-assume-role-credential-plugin#43]
I'm having an issue using this plugin to deploy resources(actually a VPC only) in `ap-east-1` region, while the same code is workable is `us-east-1` region. 

Successfully synthesized, but with the following complaints seen in the middle of the output
```
Some context information is missing. Fetching...
Reading AZs for TargetAccount:ap-east-1
AssumeRoleCredentialPlugin found value for readIamRole cdk-readOnlyRole. checking if we can obtain credentials
error assuming role AccessDenied: User: arn:aws:iam::SharedAccount:user/XXX is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:: TargetAccount:role/cdk-readOnlyRole
    at Request.extractError (/usr/local/lib/node_modules/cdk-assume-role-credential-plugin/node_modules/aws-sdk/lib/protocol/query.js:50:29)
...

```

when running `cdk deploy`, the following error occurred:
```
[Error at /EksTsDemoStack] Need to perform AWS calls for account TargetAccount, but the current credentials are for SharedAccount, and none of these plugins found any: AssumeRoleCredentialPlugin
Found errors
```

It might be related to the [STS endpoint problem](https://aws.amazon.com/premiumsupport/knowledge-center/iam-validate-access-credentials/), similar  [issue](https://github.com/aws/aws-cdk/issues/15579) .

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
