### ISSUE TITLE
AssumeRoleCredentialPlugin cannot obtain credentials for role cdk-writeRole

### ISSUE THREAD

**Issue by jobalbz** [aws-samples/cdk-assume-role-credential-plugin#50]
AssumeRoleCredentialPlugin cannot obtain credentials for role cdk-writeRole
canProvideCredentails for read role: false
canProvideCredentails for write role: false
Need to perform AWS calls for account 11111111111, but the current credentials are for 22222222222, and none of these plugins found any: AssumeRoleCredentialPlugin

**Comment by valentinsavenko** [comment]
Same issue for me

**Comment by mdesouky** [comment]
got the same issue here, to give you a picture, we have a role in cicd account that Buildkite can assume into dev and prod account, so the whole setup is working regardless of CDK, I use the plugin and configure to target the same roles that Buildkite uses to get into other accounts and it displays the same message

```
Need to perform AWS calls for account xxxxxxxxxx, but the current credentials are for yyyyyyyyyyyyy, and none of these plugins found any: AssumeRoleCredentialPlugin
```

**Comment by mdesouky** [comment]
confirm @sonac your idea to set `AWS_REGION\AWS_DEFAULT_REGION` solved this issue for me

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
