### ISSUE TITLE
Plugin doesn't assume role for target env if current AWS Profile is set to same account Id as target env

### ISSUE THREAD

**Issue by andezzat** [aws-samples/cdk-assume-role-credential-plugin#52]
So, I read thru the docs and it says if the account needing to deploy to is already the currently active one via AWS Profile etc, then the plugin won't need to assume a role to deploy to the env.

This is problematic however, because the plugin is assuming that the current AWS Profile is set to an appropriate role.
Same account, doesn't mean same role.

**Is there a way to FORCE the plugin to always attempt to assume the roles for each env?**

**Comment by corymhall** [comment]
Unfortunately this is due to how the CDK CLI works. The CLI looks for credentials for the specific AWS account and only calls out to the credential plugin if it doesn't find any.

**Comment by andezzat** [comment]
> Unfortunately this is due to how the CDK CLI works. The CLI looks for credentials for the specific AWS account and only calls out to the credential plugin if it doesn't find any.

I figured as much :(

After many headaches, I've found a workaround that doesn't involve setting up an extra AWS account outside of the 2 required for deployment or any other IAM headaches.

Just do `cdk deploy/diff/etc --profile some-fake-profile stack-name`
At first it will fail to find the profile to use it for default credentials, and so this will force a role assumption by the plugin even if the default creds are on the same account as the target stack account 👌🏽 

This might be helpful to document in the README for the plugin as I imagine other people may have similar CI/CD setups to us (running our BK agents on staging AWS account).

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
