### ISSUE TITLE
Ability to assume role into 300+ accounts

### ISSUE THREAD

**Issue by raajheshkannaa** [aws-samples/cdk-assume-role-credential-plugin#56]
Even though I'm using this plugin, I'd have to specifically mention the stack multiple times in the required-resources along with the account ids. This is ideal if we have limited number of AWS Accounts.

In the context where we have 100s of accounts, this isn't scalable. Please advise, if there is a workaround of this, until this becomes a feature where I could just a _for_ loop to iterate over boto3.Sessions with different account role credentials.

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
