### ISSUE TITLE
Unable to assume cdk-hnb659fds-lookup-role when using Vpc.fromLookup

### ISSUE THREAD

**Issue by mikelhamer** [aws-samples/cdk-assume-role-credential-plugin#57]
If I have this in my stack

``` TypeScript
    // Use existing VPC
    const vpc = ec2.Vpc.fromLookup(this, 'VPC', {
      isDefault: false
    });
```

I get the following error
``` terminal
credentials returned by plugin 'AssumeRoleCredentialPlugin' could not be used to assume 'arn:aws:iam::123456789012:role/cdk-hnb659fds-lookup-role-123456789012-us-east-2', but are for the right account. Proceeding anyway.
[Error at /PipelineStack/Dev/AppStack] You are not authorized to perform this operation.
Found errors
```

I have everything else set up correctly and am able to deploy into multiple accounts no problem using the read only deploy role using new style synthesis and all that, but it doesn't like this

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
