### ISSUE TITLE
bootstrapping using environment variable credentials fails if a shared credentials file exists

### ISSUE THREAD

**Issue by phoefflin** [aws-samples/cdk-assume-role-credential-plugin#58]
bootstrapping using credential env variables (AWS_ACCESS_KEY_ID, ...) always fails if a shared credentials file (~/.aws/credentials) exists with this error:

```
AssumeRoleCredentialPlugin cannot obtain credentials for role cdk-writeRole
canProvideCredentails for read role: false
canProvideCredentails for write role: false
 ❌  Environment aws://111111111111/eu-central-1 failed bootstrapping: Error: Need to perform AWS calls for account 111111111111, but the current credentials are for 222222222222, and none of these plugins found any: AssumeRoleCredentialPlugin
```

Turns out the credentials given in the env variables are not used due to the order of the credential provider chain.

https://github.com/aws-samples/cdk-assume-role-credential-plugin/blob/77066554a05e58fb1cf94e45a8a6791fc385095b/lib/assume-role-source.ts#L227-L242

While I understand from the comment that there is a specific reason to reorder the credential provider chain concerning the priority of `AWS.ECSCredentials()` I think it would be less surprising to stick to the default order for the rest of the chain.

**Comment by corymhall** [comment]
I am no longer planning on maintaining this repository and will be archiving it soon. I've updated the README to indicate that I no longer recommend using this plugin since the functionality has been made the default in CDK v2.
