### ISSUE TITLE
problem with default credentails and named profiles

### ISSUE THREAD

**Issue by TharaldBye** [aws-samples/cdk-assume-role-credential-plugin#7]
Hi, we are running cdk deploy with --profile my-profile option and have a named profile my-profile in aws credentials file. It looks like the plugin is looking for AWS.ECSCredentials and AWS.EnvironmentCredentials. I expected the plugin to use profile name from context and AWS.SharedIniFileCredentials to load default credentials. Getting an error Variable AWS_ACCESS_KEY_ID not set from AWS.EnvironmentCredentials when running cdk locally. I would expect the plugin to support named profiles in the credentials file without having to pass environment variables. Is there a way to solve this problem, or is possible to add AWS.SharedIniFileCredentials to the provider chain when fetching master (default) credentials in the plugin?

**Comment by corymhall** [comment]
@TharaldBye can you try it now and let me know if you still run into any issues?
